// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace angular_API.ModelsFromDB
{
    [Table("appuser")]
    public partial class Appuser
    {
        [Key]
        public long Id { get; set; }
        [Required]
        [Column("username")]
        [StringLength(256)]
        public string Username { get; set; }
    }
}